#!/bin/bash
# Copyright (c) 2020 Benjamin Holt -- MIT License

set -e  # Stop-on-error

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: git send [-a|--add] MESSAGE
                            Commit & push with message; if no files are
                            staged, modified files will be added; -a|--add
                            adds modified files regardless
       git send [-a|--add]  Show status and prompt for message before
                            sending as above
       git send -h|--help   Print this message and exit

USAGE
    exit 0
fi

Bold=`tput bold`
Off=`tput sgr0`

AddFlag=""
if [ "$1" == "-a" -o "$1" == "--add" ]; then
    AddFlag="$1"
    shift
fi

Message="$*"
if [ -z "$Message" ]; then
    git status -s
    sleep 0.1  # HACK: prompt sometimes comes out out-of-order
    if git diff-index --cached --quiet --ignore-submodules HEAD -- || [ -n "$AddFlag" ]; then
        echo "${Bold}Sending changed files${Off}"
    else
        echo "${Bold}Only sending staged changes${Off} (-a MESSAGE to add changed files)"
    fi
    echo "${Bold}Enter a message${Off} (^C or no message to cancel)"
    sleep 0.1
    read -p "${Bold}>${Off} " Message

    # Handle late -a
    StartsWith=`echo "$Message" | sed -e 's/^ *//' | cut -d ' ' -f 1`
    if [ "$StartsWith" == "-a" -o "$StartsWith" == "--add" ]; then
        AddFlag="$StartsWith"
        Message=`echo "$Message" | sed -e 's/^ *//' -e "s/^$StartsWith//" -e 's/^ *//' -e 's/ *$//'`
    fi

    if [ -z "$Message" ]; then
        echo "${Bold}Canceled${Off}"
        exit 1
    fi
fi

if git diff-index --cached --quiet --ignore-submodules HEAD -- || [ -n "$AddFlag" ]; then
    echo "${Bold}Adding changed files...${Off}"
    git add -u  # No staged changes, add unstaged files
fi

sleep 0.1
echo "${Bold}Committing...${Off}"
git commit -m "$Message"

sleep 0.1
echo "${Bold}Pulling...${Off}"
git pull -r --autostash

sleep 0.1
echo "${Bold}Pushing...${Off}"
git push

sleep 0.1
echo "${Bold}Done.${Off}"

###
