#!/bin/bash
# Copyright (c) 2020 Benjamin Holt -- MIT License

set -e  # Stop-on-error

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
Usage:  git save    Show short status, a message saying whether it will
                    automatically add changed files or just staged changes,
                    and a prompt for a commit message.  Give it a message
                    to make the commit; no message or ^C will cancel.
        git send    After saving as above, automatically pull with rebase
                    and autostash and push.
Options:
        -a|--all    Add all changed files (like 'commit -a') even if there
                    are staged changes; note that this can be given
                    "retroactively" at the message prompt.
        -m|--message MESSAGE
                    Don't show status or prompt, just do the commit with
                    the given message
        -h|--help   Print this message and exit

USAGE
    exit 0
fi

Bold=`tput bold`
Off=`tput sgr0`

AddFlag=""
if [ "$1" == "-a" -o "$1" == "--all" ]; then
    AddFlag="$1"
    shift
fi

if [ -n "$1" ] && ! [ "$1" == "-m" -o "$1" == "--message" ]; then
    echo "Unknown option $1, run 'git send -h|--help' for usage"
    exit 1
fi

Message=""
if [ "$1" == "-m" -o "$1" == "--message" ]; then
    shift
    Message="$*"
fi

if [ -z "$Message" ]; then
    git status -s
    sleep 0.1  # HACK: prompt sometimes comes out out-of-order
    if [ -n "$AddFlag" ] || git diff-index --cached --quiet --ignore-submodules HEAD --; then
        echo "${Bold}Will add changed files${Off} (but not untracked files)"
    else
        echo "${Bold}Only sending staged changes${Off} (-a MESSAGE to add changed files too)"
    fi
    echo "${Bold}Enter a message${Off} (^C or no message to cancel)"
    sleep 0.1
    read -p "${Bold}>${Off} " Message
    Message=`echo "$Message" | sed -e 's/^ *//' -e 's/ *$//'`
    # Handle ex-post-facto -a
    StartsWith=`echo "$Message" | cut -d ' ' -f 1`
    if [ "$StartsWith" == "-a" -o "$StartsWith" == "--all" ]; then
        AddFlag="$StartsWith"
        Message=`echo "$Message" | sed -e "s/^$StartsWith *//"`
    fi

    if [ -z "$Message" ]; then
        echo "${Bold}Canceled${Off}"
        exit 1
    fi
fi

if [ -n "$AddFlag" ] || git diff-index --cached --quiet --ignore-submodules HEAD --; then
    echo "${Bold}Adding changed files...${Off}"
    git add -u  # No staged changes, add unstaged files
fi

sleep 0.1
echo "${Bold}Committing...${Off}"
git commit -m "$Message"

CalledAs=`basename "$0"`
if [ "$CalledAs" == "git-send" ]; then
    sleep 0.1
    echo "${Bold}Pulling...${Off}"
    git pull -r --autostash

    sleep 0.1
    echo "${Bold}Pushing...${Off}"
    git push
fi

sleep 0.1
echo "${Bold}Done.${Off}"

###
