#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2023 Benjamin Holt -- MIT License

# Small http server that renders markdown files automatically

import argparse
import http.server

import mistletoe  # install with `pip3 install mistletoe`

class MarkdownHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path.endswith(".md"):
            self.send_response(200)
            self.send_header("Content-type", "text/html; charset=utf-8")
            self.end_headers()
            with open(self.path[1:], "r", encoding="utf-8") as f:
                self.wfile.write(mistletoe.markdown(f.read()).encode())
        else:
            super().do_GET()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Serve markdown files as rendered HTML")
    parser.add_argument("port", type=int, nargs="?", default=8910, help="Port to listen on (default: 8910)")
    args = parser.parse_args()
    http.server.test(
        HandlerClass=MarkdownHandler,
        port=args.port,
        bind="127.0.0.1",  # Only accept connections from localhost, http.server is not secure
    )
