#!/bin/bash

# Copyright (c) 2019 Benjamin Holt -- MIT License

if [ -z "$1" -o "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: newb ALIAS [SLUG]   Creates a new git branch named ALIAS and immediately
                           pushes it to a remote branch named prefix/SLUG
       newb -h|--help      Print this message and exit
USAGE
    exit 0
fi

Alias="$1"
Slug="${2:-$1}"

# $ git config [--global] user.shortname 'bjh'
: ${NewbPrefix:=`git config user.shortname || echo "$USER"`}

git checkout -b "$Alias"
git push -u origin "$Alias:$NewbPrefix/$Slug"  # FIXME: hard-coding origin

# clean up with $ git push origin -d bjh/thing
###
