#!/usr/bin/env python3

# Hacky grep-lite using Python regex

import re
import sys

def main(argv):
    pattern = re.compile(argv[1])
    if len(argv) > 2:
        file_list = argv[2:]
        for in_file in file_list:
            print(f"\n=====  {in_file}  =====", file=sys.stderr)
            with open(in_file, "r") as f:
                search(pattern, f)
    else:
        search(pattern, sys.stdin)


def search(pattern, lines):
    for l in lines:
        l = l.rstrip()
        if pattern.search(l):
            print(l)


if __name__ == "__main__":
    _xit = main(sys.argv)
    sys.exit(_xit)
