#!/usr/bin/env python3

import re

def main(argv):
    pattern = re.compile(argv[1])
    in_file = argv[2]
    with open(in_file, "r") as f:
        for l in f:
            l = l.strip()
            if pattern.search(l):
                print(l)

if __name__ == "__main__":
    import sys
    _xit = main(sys.argv)
    sys.exit(_xit)
