#!/usr/bin/env python3
# Copyright (c) 2019 Benjamin Holt -- MIT License

"""
Parse my status out of a team standup message
"""
import re

import statemachine as sm
#####


###  Main  ###
def main(args, env, inFile):
    name = args[1] if len(args) >= 2 else "bholt"
    parser = sm.StateMachine("top", unrecognized=False)
    # parser = sm.StateMachine("top")
    # parser = sm.StateMachine("top", tracer=sm.Tracer(printer=lambda s: print(f"T: {s}")))
    # parser = sm.StateMachine("top", tracer=2)
    startYesterday = ("1. What did you do yesterday?", "yesterdaySection", "_Yesterday:_")
    startToday = ("2. What do you commit to today?", "todaySection", "_Today:_")
    parser.add(None, *startYesterday)
    parser.add(None, *startToday)

    parser.add("yesterdaySection", f"@{name}", "yesterday")
    endStatus = (sm.matchTest(r"^@\w+$"), "top")
    parser.add("yesterday", *endStatus, tag="User Match")
    parser.add("yesterday", *startToday)
    statusLine = (sm.trueTest, None, lambda i,_: f"> {i}")
    parser.add("yesterday", *statusLine)

    parser.add("todaySection", f"@{name}", "today")
    parser.add("today", *endStatus, tag="User Match")
    parser.add("today", "3. How far along are you? Do you think you'll finish soon?", "top")
    parser.add("today", *statusLine)

    status = ["*Check-in*",]
    for out in parser.parse(( l.rstrip() for l in inFile )):
        status.append(out)

    print("\n".join(status))
#####


#####
if __name__ == "__main__":
    import os, sys
    if len(sys.argv) >= 2 and sys.argv[1] in ["-h", "--help"]:
        h = """Simple parser for extracting my status from a standup summary form; not likely to be useful to anyone else.

        Usage: statusparser [name]    Extract 'yesterday' and 'today' status for name; defaults to "bholt"
        """
        print(h)
        sys.exit(0)

    _xit = main(sys.argv, os.environ, sys.stdin)  # pylint: disable=invalid-name
    sys.exit(_xit)
#####
