#!/bin/bash
# Copyright (c) 2022-2025 Benjamin Holt -- MIT License

set -eo pipefail
# set -x  # Uncomment for debugging

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: tabgrab [-h|--help] [-c|--copy] [BROWSER]
       Collect tabs from all windows as a markdown list of links with
       the first tab of each window as the parent of the remaining tabs.
       The current tab is marked with ☆ and minimized windows with ▽.
       BROWSER defaults to the BROWSER_APP environment variable, otherwise
       the default handler for 'https' is used to guess the system browser.

       -c, --copy    Copies the list to the pasteboard

       -n, --num-windows N
                     Collects tabs from the first N windows, defaults to
                     all windows

       -h, --help    Print this message and exit
USAGE
    exit 0
fi

CopyList="false"
NumWindows="count (every window)"
for arg in $@; do
    case "$arg" in
        -c|--copy)
            CopyList="true"
            shift
            ;;
        -n|--num-windows)
            NumWindows="$2"
            shift 2
            ;;
    esac
done

# AppleScript Localizations
Minimized="miniaturized"
CurrentTab="current tab"

Browser="${1:-${BROWSER_APP}}"
if [ -z "$Browser" ]; then
    Handler=`defaults read ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure | (grep -B1 "LSHandlerURLScheme = https" || echo -n "") | head -1 | cut -d '"' -f 2`
    if [ -z "$Handler" -o "$Handler" == "com.apple.safari" ]; then
        Browser="Safari"
    elif [ "$Handler" == "com.google.chrome" ]; then
        Browser="Chrome"
        Minimized="minimized"
        CurrentTab="active tab"
    else
        # Try the last token of the the handler, this would work for Safari and Chrome, but doesn't work with Firefox which doesn't offer tabs in its scripting dictionary :shrug:
        Browser=`echo "$Handler" | tr '.' '\n' | tail -1`
        echo "Guessing $Browser (it may not work)" >&2
    fi
    Bold=`tput bold`
    Off=`tput sgr0`
    echo "${Bold}Grabbing tabs from ${Browser}${Off}" >&2
fi

# Hacked from [Capture all tabs in Safari as URLs to the clipboard – theconsultant.net](https://theconsultant.net/2017/06/capture-all-tabs-in-safari-as-urls-to-the-clipboard/)

osascript <<SCRIPT
tell application "$Browser"
    set tabList to ""
    set windowCount to $NumWindows
    repeat with w from 1 to windowCount
        set _window to window w
        set minMark to ""
        if _window is $Minimized then
            set minMark to "▽ "
        end if
        set currentTab to $CurrentTab of _window
        set tabCount to number of tabs in _window
        repeat with t from 1 to tabCount
            set _tab to tab t of _window
            set currentMark to ""
            if _tab is currentTab then
                set currentMark to " ☆"
            end if
            set indent to ""
            if t > 1 then
                set indent to "    "
                set minMark to ""  -- Don't add the minimized mark for child tabs
            end if
            set tabName to name of _tab
            set tabURL to URL of _tab as string
            if tabName is "" then
                set tabName to tabURL
            end if
            set tabLink to "[" & tabName & "](" & tabURL & ")"
            set tabList to tabList & indent & "- " & minMark & tabLink & currentMark & linefeed as string
        end repeat
        set tabList to tabList & linefeed
    end repeat
    if $CopyList then
        set the clipboard to the tabList
        return "Copied"
    else
        return tabList
    end if
end tell
SCRIPT
