#!/bin/zsh

###  Environment Variables  ###
export PATH="$HOME/.local/bin:${PATH}"

# Go lang
export PATH="$PATH:$HOME/go/bin"

# Rust
export PATH="$PATH:$HOME/.cargo/bin"

# Inventhouse Tools
export PATH="$PATH:$INVENTHUB/allgit:$INVENTHUB/bettergit:$INVENTHUB/BenBin"

# Homebrew
if `which brew 2>&1 >> /dev/null`; then
    eval "$(brew shellenv)"
fi

# Use helix editor if available
if which "hx" 2>&1 >> /dev/null; then
    export EDITOR="hx"
fi

export GIT_SSH_COMMAND="ssh -o ConnectTimeout=10 -o ServerAliveInterval=5 -o ServerAliveCountMax=2"

export PENSIEVE_DIR="$INVENTHUB/bjh-pensieve"
export TABDUMP_DIR="$PENSIEVE_DIR/Notes/Tabdumps"
export NOTES_FILE="$PENSIEVE_DIR/Notes/000Notes.md"
# export TODO_FILE="$PENSIEVE_DIR/Notes/000ToDo.md"
# export BLUETAPE_FILE="$PENSIEVE_DIR/Notes/BlueTape.md"
#####
