#!/bin/zsh
###  Basic Aliases  ###
alias ag='allgit'
if which allgit.py 2>&1 >> /dev/null; then  # Use the dev version if available
    alias ag='allgit.py'
fi

alias uvr='uv run'
alias venv='python3 -m venv'
alias dkc='docker-compose'
alias tf='terraform'

alias serve='python -m http.server -b 127.0.0.1'

# Requires BenBin/tabgrab and `brew install cloc`
# HACK: "sed '$d'" drops the last line so the blank count matches the number of windows
# REM: perhaps tabgrab should natively support a count mode
alias tabcount='tabgrab | sed '$d' | cloc - --stdin-name=tabs.md | grep "Markdown" | cut -wf 3,5'
alias tabhunt='tabgrab | less'

if [ -f "$NOTES_FILE" ]; then
    alias topnote='intake "$NOTES_FILE" "# --- Top ---" "-"'
fi
if [ -f "$TODO_FILE" ]; then
    alias todo='intake "$TODO_FILE"'
fi
if [ -f "$BLUETAPE_FILE" ]; then
    alias bluetape='intake "$BLUETAPE_FILE"'
fi
#####


###  Pasteboard Aliases  ###
alias pbq='pbpaste | sed -e "s/^/> /" | pbcopy'  # pb quote
alias pbc='pbpaste | sed -e "s/ # .*//" -e "s/^#.*//" -e "/^ *$/d" | pbcopy'  # pb strip comments

alias pbless='pbpaste | less'
alias pbwc='pbpaste | wc'

alias pbtabs='tabgrab -n 1 | pbcopy'

# Convert e.g. module/sub/file.py to module.sub.file
alias pbdotpath='pbpaste | sed -e "s/\\.[^.]*$//" | tr "/" "." | pbcopy'

alias pblower='pbpaste | tr 'A-Z' 'a-z' | pbcopy'
alias pbupper='pbpaste | tr 'a-z' 'A-Z' | pbcopy'

alias pbsort='pbpaste | sort | pbcopy'
alias pbwrap='pbpaste | fmt -72 | pbcopy'
alias pbunwrap="pbpaste | awk -v RS='' -v ORS='\n\n' '{gsub(/\n/, \" \"); print}' | pbcopy"

alias pbxml='pbpaste | xmllint --format - | pbcopy'
alias pbjson='pbpaste | jq . | pbcopy'

# Requires `brew install sqlfluff`
pbsql() {
    # Fix what can be fixed easily...
    pbpaste | sqlfluff fix --dialect postgres - | pbcopy
    # ...if there are still issues, lint will print line numbers...
    if ! pbpaste | sqlfluff lint --dialect postgres -; then
        # ...in that case also print numbered lines
        pbpaste | cat -n
    fi
}
#####
